//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOI.PI.MusicBandApp.Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class hr_HR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal hr_HR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOI.PI.MusicBandApp.Desktop.Resources.hr-HR", typeof(hr_HR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bend je uspješno izbrisan.
        /// </summary>
        internal static string BandDeletedSucessfully {
            get {
                return ResourceManager.GetString("BandDeletedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bend je uspješno ažuriran.
        /// </summary>
        internal static string BandUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("BandUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervaciju nije moguće potvrditi! Provjerite da li postoji iznos te da li je status &apos;Zatrazena&apos;.
        /// </summary>
        internal static string CannotSubmitReservation {
            get {
                return ResourceManager.GetString("CannotSubmitReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum &apos;od&apos; je veći od datuma &apos;do&apos;.
        /// </summary>
        internal static string DateToGreaterIsThanDateFrom {
            get {
                return ResourceManager.GetString("DateToGreaterIsThanDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešna putanja do slike.
        /// </summary>
        internal static string ImageNotValid {
            get {
                return ResourceManager.GetString("ImageNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail nije u pravilnom formatu.
        /// </summary>
        internal static string IncorrectEmailFormat {
            get {
                return ResourceManager.GetString("IncorrectEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj nije u ispravnom formazu.
        /// </summary>
        internal static string IncorrectNumberFormat {
            get {
                return ResourceManager.GetString("IncorrectNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje je u pogrešnom formatu (Ispravan format: &apos;HH:mm:ss&apos;).
        /// </summary>
        internal static string IncorrectTimeSpanFormat {
            get {
                return ResourceManager.GetString("IncorrectTimeSpanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popunite sva polja.
        /// </summary>
        internal static string InsertAllValues {
            get {
                return ResourceManager.GetString("InsertAllValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervacija mora biti u statusu &apos;Zatrazena&apos;.
        /// </summary>
        internal static string InvalidReservationStatus {
            get {
                return ResourceManager.GetString("InvalidReservationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail se već koristi.
        /// </summary>
        internal static string MailAlreadyTaken {
            get {
                return ResourceManager.GetString("MailAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Član je uspješno dodan.
        /// </summary>
        internal static string MemberAddedSuccessfully {
            get {
                return ResourceManager.GetString("MemberAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Član je uspješno izbrisan.
        /// </summary>
        internal static string MemberDeletedSuccessfully {
            get {
                return ResourceManager.GetString("MemberDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite iznos.
        /// </summary>
        internal static string PriceMissing {
            get {
                return ResourceManager.GetString("PriceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija uspješno provedena!.
        /// </summary>
        internal static string RegisteredSuccessfully {
            get {
                return ResourceManager.GetString("RegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervacija uspješno odbačena.
        /// </summary>
        internal static string ReservationCanceledSuccessfully {
            get {
                return ResourceManager.GetString("ReservationCanceledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervacija uspješno odbačena.
        /// </summary>
        internal static string ReservationDismissed {
            get {
                return ResourceManager.GetString("ReservationDismissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena rezervacije postavljena uspješno.
        /// </summary>
        internal static string ReservationSaved {
            get {
                return ResourceManager.GetString("ReservationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervacija je uspješno poslana.
        /// </summary>
        internal static string ReservationSentSuccessfully {
            get {
                return ResourceManager.GetString("ReservationSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervacija uspješno dogovorena.
        /// </summary>
        internal static string ReservationSubmittedSuccessfully {
            get {
                return ResourceManager.GetString("ReservationSubmittedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezultat sadrži više od očekivanog broja rezultata!.
        /// </summary>
        internal static string ResultSetHasMultipleValues {
            get {
                return ResourceManager.GetString("ResultSetHasMultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pjesma uspješno dodana.
        /// </summary>
        internal static string SongAddedSuccessfully {
            get {
                return ResourceManager.GetString("SongAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pjesma uspješno uklonjena.
        /// </summary>
        internal static string SongRemovedSuccessfully {
            get {
                return ResourceManager.GetString("SongRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešan mail ili lozinka.
        /// </summary>
        internal static string UnknownUser {
            get {
                return ResourceManager.GetString("UnknownUser", resourceCulture);
            }
        }
    }
}
